name: Unit/integration tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - run: mvn test
